server:
  port: 9021
logging.config: classpath:logback-spring-@profileActive@.xml

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/ext/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  profiles:
    active: @profileActive@
    include: dev,test,prod
  jmx:
    enabled: false
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb

management:
  health:
    refresh:
      enabled: true
    db:
      enabled: false
    rabbit:
      enabled: false

endpoints:
  enabled: false
  health:
    enabled: true
    sensitive: false
